# HERE IS AN INTRODUCTION TO NUMPY

Source Lecture: PIERAN DATA

PARTICULARLY HOW TO CREATE NUMPY ARRAYS AND SOME BASIC ATTRIBUTES AND METHODS

In [1]:
# I begin by importing numpy as np which I will use to refernce throughout the notebook
import numpy as np



## How to Create a Numpy Array




### 1. From a Python List

We can create an array by directly converting a list or list of lists using np.array(pass in a list/lol)

In [2]:
myList = [1,2,3,4, 5]
myList

[1, 2, 3, 4, 5]

In [3]:
# Casting lists as arrays
np.array(myList)

array([1, 2, 3, 4, 5])

In [4]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
#Casting a matrix as an array
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2. By using Built-in Methods


### A. arange

This returns evenly spaced values within a given interval.

In [6]:
# np.arange(start-point, stop-point(excludig), step-size(optional))
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### B. zeros and ones

You can generate arrays of zeros or ones

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### C. linspace
This returns evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## D. eye

Creates an identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## E. Random 

Numpy also has lots of ways to create random number arrays:



### 1. rand
This creates an array of the given shape and populates it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(2)

array([0.65665785, 0.11557152])

In [16]:
np.random.rand(5,5)

array([[0.19086853, 0.71554726, 0.30953987, 0.62295167, 0.07327557],
       [0.02346441, 0.09338457, 0.49840498, 0.4826079 , 0.04524288],
       [0.43053718, 0.37497417, 0.15582648, 0.89094554, 0.63740067],
       [0.34847324, 0.88499529, 0.15645975, 0.8022882 , 0.51895745],
       [0.49382214, 0.81501804, 0.0437962 , 0.6808145 , 0.10986002]])

### 3. randn

This returns a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(3)

array([ 0.74715056, -0.428299  ,  0.567739  ])

In [18]:
np.random.randn(6,6)

array([[ 0.95449401, -0.15879547,  0.78250625, -0.28863831,  1.28770627,
        -0.95729655],
       [-3.55459004, -1.94974864,  0.11078851, -2.39137363, -0.05246497,
         0.31291654],
       [-0.12721518, -1.28291769, -0.99163983,  0.60740153,  1.04448202,
        -0.02206607],
       [ 0.88555431, -0.45214769, -1.56965834, -0.02497836,  0.77742759,
         1.2225162 ],
       [-1.35233938, -0.01049096, -0.25330033, -1.01815968, -1.15877563,
        -0.32608128],
       [ 1.74290938, -0.98983351, -0.96367699, -0.57821437, -1.36483251,
         1.24681713]])

### 4. randint
This returns random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,100)

21

In [20]:
np.random.randint(1,100,10)

array([89, 17, 54, 27, 31, 30, 99, 40, 95, 39])

## Array Attributes and Methods


In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([28, 20, 28, 46, 14,  3,  1,  5, 45, 46])

## A. Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### More... 
#### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr

array([28, 20, 28, 46, 14,  3,  1,  5, 45, 46])

In [26]:
# Returns the maximum value from an Array
ranarr.max()

46

In [27]:
# Returns the argmax value from an Array
ranarr.argmax()

3

In [28]:
# Returns the minimum value from an Array
ranarr.min()

1

In [29]:
# Returns the argmin value from an Array
ranarr.argmin()

6

## B. Shape

Shape is an attribute that arrays have (not a method):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
# make sure dimension match the array size
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int64')

# THE END 😎